openapi: 3.0.3
info:
  description: API documentation for Wallos
  title: Wallos API
  version: 1.0.0
  x-logo:
    url: https://wallosapp.com/images/logo/wallosapi.png
    altText: Wallos API Logo
servers:
- url: /
paths:
  /api/admin/get_admin_settings.php:
    get:
      description: Retrieve admin settings from the Wallos application.
      parameters:
      - description: API key of the user.
        in: query
        name: api_key
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_admin_get_admin_settings_php_get_200_response'
          description: Successful response
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_admin_get_admin_settings_php_get_401_response'
          description: Unauthorized - Invalid API Key
      summary: Get Admin Settings
  /api/categories/get_categories.php:
    get:
      description: Retrieve a list of categories from the Wallos application.
      parameters:
      - description: API key of the user.
        in: query
        name: api_key
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_categories_get_categories_php_get_200_response'
          description: Successful response
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_admin_get_admin_settings_php_get_401_response'
          description: Unauthorized - Invalid API Key
      summary: Get Categories
  /api/currencies/get_currencies.php:
    get:
      description: Retrieve a list of currencies and the main currency of the user.
      parameters:
      - description: API key of the user.
        in: query
        name: api_key
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_currencies_get_currencies_php_get_200_response'
          description: Successful response
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_admin_get_admin_settings_php_get_401_response'
          description: Unauthorized - Invalid API Key
      summary: Get Currencies
  /api/fixer/get_fixer.php:
    get:
      description: Retrieve the Fixer settings for the user.
      parameters:
      - description: API key of the user.
        in: query
        name: api_key
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_fixer_get_fixer_php_get_200_response'
          description: Successful response
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_admin_get_admin_settings_php_get_401_response'
          description: Unauthorized - Invalid API Key
      summary: Get Fixer Settings
  /api/household/get_household.php:
    get:
      description: Retrieve the household members.
      parameters:
      - in: query
        name: api_key
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_household_get_household_php_get_200_response'
          description: Successful response
      summary: Get Household
  /api/notifications/get_notification_settings.php:
    get:
      description: Retrieve the notification settings for the enabled methods.
      parameters:
      - in: query
        name: api_key
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_notifications_get_notification_settings_php_get_200_response'
          description: Successful response
      summary: Get Notification Settings
  /api/payment_methods/get_payment_methods.php:
    get:
      description: Retrieve the available payment methods.
      parameters:
      - in: query
        name: api_key
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_payment_methods_get_payment_methods_php_get_200_response'
          description: Successful response
      summary: Get Payment Methods
  /api/settings/get_settings.php:
    get:
      description: Retrieve the user settings.
      parameters:
      - in: query
        name: api_key
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_settings_get_settings_php_get_200_response'
          description: Successful response
      summary: Get User Settings
  /api/subscriptions/get_monthly_cost.php:
    get:
      description: Retrieve the total cost of subscriptions for a specific month and
        year.
      parameters:
      - description: The API key of the user.
        in: query
        name: api_key
        required: true
        schema:
          type: string
      - description: The month for which the cost is to be calculated.
        in: query
        name: month
        required: true
        schema:
          type: integer
      - description: The year for which the cost is to be calculated.
        in: query
        name: year
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_subscriptions_get_monthly_cost_php_get_200_response'
          description: Successful response with monthly cost details.
      summary: Get Monthly Cost
  /api/subscriptions/get_subscriptions.php:
    get:
      description: Retrieve a list of subscriptions with optional filters.
      parameters:
      - description: The API key of the user.
        in: query
        name: api_key
        required: true
        schema:
          type: string
      - description: Comma-separated IDs of the members to filter.
        in: query
        name: member
        required: false
        schema:
          type: string
      - description: The ID of the category to filter.
        in: query
        name: category
        required: false
        schema:
          type: integer
      - description: The ID of the payment method to filter.
        in: query
        name: payment_method
        required: false
        schema:
          type: integer
      - description: "The state of the subscription to filter [0 - active, 1 - inactive]."
        in: query
        name: state
        required: false
        schema:
          type: boolean
      - description: Whether to sort inactive subscriptions to the bottom.
        in: query
        name: disabled_to_bottom
        required: false
        schema:
          type: boolean
      - description: "The sorting method ['name', 'id', 'next_payment', 'price', etc.]."
        in: query
        name: sort
        required: false
        schema:
          enum:
          - name
          - id
          - next_payment
          - price
          - payer_user_id
          - category_id
          - payment_method_id
          - inactive
          - alphanumeric
          type: string
      - description: Whether to convert the prices to the main currency.
        in: query
        name: convert_currency
        required: false
        schema:
          type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_api_subscriptions_get_subscriptions_php_get_200_response'
          description: Successful response with subscription details.
      summary: Get Subscriptions
components:
  schemas:
    _api_admin_get_admin_settings_php_get_200_response_admin_settings:
      example:
        from_email: from_email
        smtp_address: smtp_address
        registrations_open: 0
        max_users: 6
        require_email_verification: 1
        smtp_username: smtp_username
        login_disabled: 5
        smtp_port: 5
        smtp_password: smtp_password
        encryption: encryption
        latest_version: latest_version
        update_notification: 2
        server_url: https://openapi-generator.tech
      properties:
        registrations_open:
          description: "Indicates if registrations are open (1 for true, 0 for false)."
          type: integer
        max_users:
          description: The maximum number of users allowed.
          type: integer
        require_email_verification:
          description: "Indicates if email verification is required (1 for true, 0\
            \ for false)."
          type: integer
        server_url:
          description: The server URL.
          format: uri
          type: string
        smtp_address:
          description: The SMTP address for sending emails.
          type: string
        smtp_port:
          description: The port for the SMTP server.
          type: integer
        smtp_username:
          description: The username for SMTP authentication.
          type: string
        smtp_password:
          description: The password for SMTP authentication.
          type: string
        from_email:
          description: The email address used as the sender.
          format: email
          type: string
        encryption:
          description: "The encryption method for SMTP (e.g., tls, ssl)."
          type: string
        login_disabled:
          description: "Indicates if login is disabled (1 for true, 0 for false)."
          type: integer
        latest_version:
          description: The latest version of the application.
          type: string
        update_notification:
          description: "Indicates if update notifications are enabled (1 for true,\
            \ 0 for false)."
          type: integer
      type: object
    _api_categories_get_categories_php_get_200_response:
      example:
        notes:
        - notes
        - notes
        success: true
        categories:
        - name: name
          in_use: true
          id: 0
          order: 6
        - name: name
          in_use: true
          id: 0
          order: 6
        title: title
      properties:
        success:
          description: Indicates whether the request was successful.
          type: boolean
        title:
          description: The title of the response.
          type: string
        categories:
          items:
            $ref: '#/components/schemas/_api_categories_get_categories_php_get_200_response_categories_inner'
          type: array
        notes:
          description: Warning messages or additional information.
          items:
            type: string
          type: array
      type: object
    _api_notifications_get_notification_settings_php_get_200_response:
      example:
        notes:
        - notes
        - notes
        success: true
        notification_settings:
          email_notifications:
            from_email: from_email
            smtp_port: 6
            smtp_password: smtp_password
            encryption: encryption
            smtp_address: smtp_address
            other_emails: other_emails
            enabled: 0
            smtp_username: smtp_username
          ntfy_notifications:
            headers: headers
            host: host
            topic: topic
            enabled: 1
        title: title
      properties:
        success:
          type: boolean
        title:
          type: string
        notification_settings:
          $ref: '#/components/schemas/_api_notifications_get_notification_settings_php_get_200_response_notification_settings'
        notes:
          items:
            type: string
          type: array
      type: object
    _api_categories_get_categories_php_get_200_response_categories_inner:
      example:
        name: name
        in_use: true
        id: 0
        order: 6
      properties:
        id:
          description: The unique identifier for the category.
          type: integer
        name:
          description: The name of the category.
          type: string
        order:
          description: The display order of the category.
          type: integer
        in_use:
          description: Indicates if the category is currently in use.
          type: boolean
      type: object
    _api_notifications_get_notification_settings_php_get_200_response_notification_settings_email_notifications:
      example:
        from_email: from_email
        smtp_port: 6
        smtp_password: smtp_password
        encryption: encryption
        smtp_address: smtp_address
        other_emails: other_emails
        enabled: 0
        smtp_username: smtp_username
      properties:
        enabled:
          type: integer
        smtp_address:
          type: string
        smtp_port:
          type: integer
        smtp_username:
          type: string
        smtp_password:
          type: string
        from_email:
          type: string
        encryption:
          type: string
        other_emails:
          type: string
      type: object
    _api_subscriptions_get_monthly_cost_php_get_200_response:
      example:
        monthly_cost: 0.8008282
        notes:
        - notes
        - notes
        currency_symbol: currency_symbol
        success: true
        title: title
        localized_monthly_cost: localized_monthly_cost
        currency_code: currency_code
      properties:
        success:
          description: Whether the request was successful.
          type: boolean
        title:
          description: "A string representing the month and year (e.g., March 2025)."
          type: string
        monthly_cost:
          description: The total cost for the specified month.
          format: float
          type: number
        localized_monthly_cost:
          description: The total cost formatted according to the user's locale and
            currency.
          type: string
        currency_code:
          description: The currency code of the user's main currency.
          type: string
        currency_symbol:
          description: The currency symbol of the user's main currency.
          type: string
        notes:
          description: Warning messages or additional information.
          items:
            type: string
          type: array
      type: object
    _api_payment_methods_get_payment_methods_php_get_200_response_payment_methods_inner:
      example:
        name: name
        icon: icon
        in_use: true
        id: 0
        enabled: 6
        order: 1
      properties:
        id:
          type: integer
        name:
          type: string
        icon:
          type: string
        enabled:
          type: integer
        order:
          type: integer
        in_use:
          type: boolean
      type: object
    _api_admin_get_admin_settings_php_get_401_response:
      example:
        notes:
        - Invalid API Key
        success: false
        title: Unauthorized
      properties:
        success:
          example: false
          type: boolean
        title:
          example: Unauthorized
          type: string
        notes:
          example:
          - Invalid API Key
          items:
            type: string
          type: array
      type: object
    _api_fixer_get_fixer_php_get_200_response_fixer:
      example:
        api_key: api_key
        provider: 0
        provider_name: provider_name
      properties:
        api_key:
          description: The API key used for accessing Fixer.
          type: string
        provider:
          description: The ID of the provider.
          type: integer
        provider_name:
          description: The name of the provider.
          type: string
      type: object
    _api_household_get_household_php_get_200_response:
      example:
        notes:
        - notes
        - notes
        success: true
        household:
        - name: name
          in_use: true
          id: 0
          email: email
        - name: name
          in_use: true
          id: 0
          email: email
        title: title
      properties:
        success:
          type: boolean
        title:
          type: string
        household:
          items:
            $ref: '#/components/schemas/_api_household_get_household_php_get_200_response_household_inner'
          type: array
        notes:
          items:
            type: string
          type: array
      type: object
    _api_payment_methods_get_payment_methods_php_get_200_response:
      example:
        payment_methods:
        - name: name
          icon: icon
          in_use: true
          id: 0
          enabled: 6
          order: 1
        - name: name
          icon: icon
          in_use: true
          id: 0
          enabled: 6
          order: 1
        notes:
        - notes
        - notes
        success: true
        title: title
      properties:
        success:
          type: boolean
        title:
          type: string
        payment_methods:
          items:
            $ref: '#/components/schemas/_api_payment_methods_get_payment_methods_php_get_200_response_payment_methods_inner'
          type: array
        notes:
          items:
            type: string
          type: array
      type: object
    _api_settings_get_settings_php_get_200_response_settings_custom_css:
      example:
        css: css
      properties:
        css:
          type: string
      type: object
    _api_admin_get_admin_settings_php_get_200_response:
      example:
        notes:
        - notes
        - notes
        success: true
        title: title
        admin_settings:
          from_email: from_email
          smtp_address: smtp_address
          registrations_open: 0
          max_users: 6
          require_email_verification: 1
          smtp_username: smtp_username
          login_disabled: 5
          smtp_port: 5
          smtp_password: smtp_password
          encryption: encryption
          latest_version: latest_version
          update_notification: 2
          server_url: https://openapi-generator.tech
      properties:
        success:
          description: Indicates whether the request was successful.
          type: boolean
        title:
          description: The title of the response.
          type: string
        admin_settings:
          $ref: '#/components/schemas/_api_admin_get_admin_settings_php_get_200_response_admin_settings'
        notes:
          description: Warning messages or additional information.
          items:
            type: string
          type: array
      type: object
    _api_currencies_get_currencies_php_get_200_response_currencies_inner:
      example:
        symbol: symbol
        code: code
        rate: rate
        name: name
        in_use: true
        id: 6
      properties:
        id:
          description: The unique identifier for the currency.
          type: integer
        name:
          description: The name of the currency.
          type: string
        symbol:
          description: The symbol of the currency.
          type: string
        code:
          description: The ISO code of the currency.
          type: string
        rate:
          description: The current exchange rate of the currency.
          type: string
        in_use:
          description: Indicates if the currency is currently in use.
          type: boolean
      type: object
    _api_notifications_get_notification_settings_php_get_200_response_notification_settings:
      example:
        email_notifications:
          from_email: from_email
          smtp_port: 6
          smtp_password: smtp_password
          encryption: encryption
          smtp_address: smtp_address
          other_emails: other_emails
          enabled: 0
          smtp_username: smtp_username
        ntfy_notifications:
          headers: headers
          host: host
          topic: topic
          enabled: 1
      properties:
        email_notifications:
          $ref: '#/components/schemas/_api_notifications_get_notification_settings_php_get_200_response_notification_settings_email_notifications'
        ntfy_notifications:
          $ref: '#/components/schemas/_api_notifications_get_notification_settings_php_get_200_response_notification_settings_ntfy_notifications'
      type: object
    _api_settings_get_settings_php_get_200_response_settings:
      example:
        remove_background: 5
        monthly_price: 6
        disabled_to_bottom: 2
        show_original_price: 7
        hide_disabled: 5
        custom_css:
          css: css
        mobile_nav: 9
        color_theme: color_theme
        dark_theme: 0
        convert_currency: 1
      properties:
        dark_theme:
          type: integer
        monthly_price:
          type: integer
        convert_currency:
          type: integer
        remove_background:
          type: integer
        color_theme:
          type: string
        hide_disabled:
          type: integer
        disabled_to_bottom:
          type: integer
        show_original_price:
          type: integer
        mobile_nav:
          type: integer
        custom_css:
          $ref: '#/components/schemas/_api_settings_get_settings_php_get_200_response_settings_custom_css'
      type: object
    _api_notifications_get_notification_settings_php_get_200_response_notification_settings_ntfy_notifications:
      example:
        headers: headers
        host: host
        topic: topic
        enabled: 1
      properties:
        enabled:
          type: integer
        host:
          type: string
        topic:
          type: string
        headers:
          type: string
      type: object
    _api_currencies_get_currencies_php_get_200_response:
      example:
        main_currency: 0
        notes:
        - notes
        - notes
        success: true
        title: title
        currencies:
        - symbol: symbol
          code: code
          rate: rate
          name: name
          in_use: true
          id: 6
        - symbol: symbol
          code: code
          rate: rate
          name: name
          in_use: true
          id: 6
      properties:
        success:
          description: Indicates whether the request was successful.
          type: boolean
        title:
          description: The title of the response.
          type: string
        main_currency:
          description: The ID of the main currency of the user.
          type: integer
        currencies:
          items:
            $ref: '#/components/schemas/_api_currencies_get_currencies_php_get_200_response_currencies_inner'
          type: array
        notes:
          description: Warning messages or additional information.
          items:
            type: string
          type: array
      type: object
    _api_subscriptions_get_subscriptions_php_get_200_response:
      example:
        subscriptions:
        - notes: notes
          category_name: category_name
          notify_days_before: 3
          cancelation_date: 2000-01-23
          payer_user_name: payer_user_name
          payment_method_name: payment_method_name
          cycle: 5
          notify: true
          url: url
          frequency: 5
          next_payment: 2000-01-23
          payment_method_id: 2
          inactive: true
          category_id: 9
          price: 6.0274563
          name: name
          logo: logo
          id: 0
          payer_user_id: 7
          currency_id: 1
        - notes: notes
          category_name: category_name
          notify_days_before: 3
          cancelation_date: 2000-01-23
          payer_user_name: payer_user_name
          payment_method_name: payment_method_name
          cycle: 5
          notify: true
          url: url
          frequency: 5
          next_payment: 2000-01-23
          payment_method_id: 2
          inactive: true
          category_id: 9
          price: 6.0274563
          name: name
          logo: logo
          id: 0
          payer_user_id: 7
          currency_id: 1
        notes:
        - notes
        - notes
        success: true
        title: title
      properties:
        success:
          description: Whether the request was successful.
          type: boolean
        title:
          description: "The title of the response, typically 'subscriptions'."
          type: string
        subscriptions:
          items:
            $ref: '#/components/schemas/_api_subscriptions_get_subscriptions_php_get_200_response_subscriptions_inner'
          type: array
        notes:
          description: Warning messages or additional information.
          items:
            type: string
          type: array
      type: object
    _api_subscriptions_get_subscriptions_php_get_200_response_subscriptions_inner:
      example:
        notes: notes
        category_name: category_name
        notify_days_before: 3
        cancelation_date: 2000-01-23
        payer_user_name: payer_user_name
        payment_method_name: payment_method_name
        cycle: 5
        notify: true
        url: url
        frequency: 5
        next_payment: 2000-01-23
        payment_method_id: 2
        inactive: true
        category_id: 9
        price: 6.0274563
        name: name
        logo: logo
        id: 0
        payer_user_id: 7
        currency_id: 1
      properties:
        id:
          type: integer
        name:
          type: string
        logo:
          type: string
        price:
          format: float
          type: number
        currency_id:
          type: integer
        next_payment:
          format: date
          type: string
        cycle:
          type: integer
        frequency:
          type: integer
        notes:
          type: string
        payment_method_id:
          type: integer
        payer_user_id:
          type: integer
        category_id:
          type: integer
        notify:
          type: boolean
        url:
          type: string
        inactive:
          type: boolean
        notify_days_before:
          type: integer
        cancelation_date:
          format: date
          type: string
        category_name:
          type: string
        payer_user_name:
          type: string
        payment_method_name:
          type: string
      type: object
    _api_fixer_get_fixer_php_get_200_response:
      example:
        notes:
        - notes
        - notes
        success: true
        title: title
        fixer:
          api_key: api_key
          provider: 0
          provider_name: provider_name
      properties:
        success:
          description: Indicates whether the request was successful.
          type: boolean
        title:
          description: The title of the response.
          type: string
        fixer:
          $ref: '#/components/schemas/_api_fixer_get_fixer_php_get_200_response_fixer'
        notes:
          description: Warning messages or additional information.
          items:
            type: string
          type: array
      type: object
    _api_household_get_household_php_get_200_response_household_inner:
      example:
        name: name
        in_use: true
        id: 0
        email: email
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        in_use:
          type: boolean
      type: object
    _api_settings_get_settings_php_get_200_response:
      example:
        settings:
          remove_background: 5
          monthly_price: 6
          disabled_to_bottom: 2
          show_original_price: 7
          hide_disabled: 5
          custom_css:
            css: css
          mobile_nav: 9
          color_theme: color_theme
          dark_theme: 0
          convert_currency: 1
        notes:
        - notes
        - notes
        success: true
        title: title
      properties:
        success:
          type: boolean
        title:
          type: string
        settings:
          $ref: '#/components/schemas/_api_settings_get_settings_php_get_200_response_settings'
        notes:
          items:
            type: string
          type: array
      type: object
